### ISSUE TITLE
Error no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by davefogo** [RailsApps/rails_layout#26]
Hello,

When I tried to run the $ rails generate layout:devise bootstrap3 following the Devise QuickStart tutorial and I got the following error:
Please help me find a solution. Been searching online for 2 hours.

update: 
Aslo received the exact same error while running:
rails generate pages:home
rails s

It seems the issue is with the adding of =
 Devise Initializer

Rails Composer makes one minor change to the Devise initializer file config/initializers/devise.rb:
config.mailer_sender = 'no-reply@' + Rails.application.secrets.domain_name

Thank you for your help

/Users/davefogo/Sites/ideapp/config/initializers/devise.rb:13:in `+': no implicit conversion of nil into String (TypeError)
	from /Users/davefogo/Sites/ideapp/config/initializers/devise.rb:13:in `block in <top (required)>'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise.rb:293:in `setup'
	from /Users/davefogo/Sites/ideapp/config/initializers/devise.rb:3:in `<top (required)>'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:418:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:417:in `block in each_strongly_connected_component_from'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:411:in `call'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:411:in `each_strongly_connected_component_from'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /Users/davefogo/Sites/ideapp/config/environment.rb:5:in `<top (required)>'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/application.rb:92:in `preload'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/application.rb:143:in `serve'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/application.rb:131:in `block in run'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/application.rb:125:in `loop'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/application.rb:125:in `run'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/spring-1.3.3/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/davefogo/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by davefogo** [comment]
Hello is someone supporting this gem? Thank you

**Comment by DanielKehoe** [comment]
Sorry for the slow response. I am traveling with limited Internet access now.

**Comment by DanielKehoe** [comment]
I haven't been able to reproduce your issue. I'm using Ruby 2.2.0p0 and Rails 4.2.1. I create a new app with
```
$ rails new rails-devise -m https://raw.github.com/RailsApps/rails-composer/master/composer.rb
```
and then run
```
$ rails generate layout:devise bootstrap3
```
without any error.

Do you have a file *config/secrets.yml*? Does it contain:
```
development:
  .
  .
  .
  domain_name: example.com
```

**Comment by davefogo** [comment]
Hello and thank you for your response

I don't have any secrets configured. I don't have a domain config in
development. I have my own so and have been trying to mimic all parts Rails
composer with no success.

What can I do to help you see my issue? It fails when I change the devise
file to the @no reply in one of the steps.

**Comment by DanielKehoe** [comment]
The rails_layout gem expects you to have a *config/secrets.yml* file with the ```Rails.application.secrets.domain_name``` value set. Set the value in your *config/secrets.yml* file and you can use the rails_layout gem. Use ```example.com``` if you don't have another value.

**Comment by davefogo** [comment]
Thank you
