### ISSUE TITLE
A view file is missing

### ISSUE THREAD

**Issue by razukc** [RailsApps/rails_layout#30]
The following command
  rails generate layout:devise foundation5
misses to create
  app/views/devise/registrations/new.html.erb

**Comment by DanielKehoe** [comment]
I'm unable to reproduce this issue:

````
$ rails generate layout:devise foundation5
      create  app/views/devise/sessions/new.html.erb
      create  app/views/devise/passwords/new.html.erb
      create  app/views/devise/passwords/edit.html.erb
      create  app/views/devise/registrations/new.html.erb
      create  app/views/devise/registrations/edit.html.erb
$
````
It looks like the file ```app/views/devise/registrations/new.html.erb``` is there.

Have I missed something?

**Comment by razukc** [comment]
May be something wrong on my part, then.
